name: GROQ_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.10.10
  - aiosignal=1.3.1
  - altair=5.0.1
  - annotated-types=0.7.0
  - anyio=4.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asgiref=3.8.1
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - babel=2.11.0
  - backoff=2.2.1
  - bcrypt=4.2.0
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - blinker=1.8.2
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.1
  - ca-certificates=2024.9.24
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - chroma-hnswlib=0.7.6
  - chromadb=0.5.13
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.1
  - cryptography=43.0.1
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.2.1.18
  - dataclasses-json=0.6.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.14
  - distro=1.9.0
  - dlfcn-win32=1.4.1
  - dnspython=2.7.0
  - durationpy=0.9
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=0.8.3
  - fastapi=0.115.2
  - fastapi-cli=0.0.5
  - filelock=3.16.1
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2024.9.0
  - gitdb=4.0.7
  - gitpython=3.1.43
  - google-auth=2.35.0
  - googleapis-common-protos=1.65.0
  - greenlet=3.1.1
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.6
  - httptools=0.6.1
  - httpx=0.27.2
  - huggingface_hub=0.25.2
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=7.0.2
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - intel-openmp=2024.2.1
  - invoke=1.6.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - jiter=0.6.1
  - jpeg=9e
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - krb5=1.21.3
  - langchain=0.2.16
  - langchain-chroma=0.1.4
  - langchain-community=0.2.16
  - langchain-core=0.2.40
  - langchain-openai=0.1.25
  - langchain-text-splitters=0.2.4
  - langsmith=0.1.129
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libdeflate=1.17
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libparquet=16.1.0
  - libpng=1.6.44
  - libprotobuf=4.25.3
  - libpulsar=3.5.1
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.4.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzlib-wapi=1.3.1
  - loguru=0.7.2
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown-it-py=3.0.0
  - markupsafe=3.0.1
  - marshmallow=3.22.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=2.0.4
  - mkl=2024.1.0
  - mmh3=5.0.1
  - monotonic=1.5
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.1.0
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-connector-python=9.0.0
  - mysql-libs=9.0.1
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numpy=1.26.4
  - oauthlib=3.2.2
  - onnxruntime=1.18.1
  - openai=1.51.2
  - openjpeg=2.5.0
  - openssl=3.3.2
  - opentelemetry-api=1.27.0
  - opentelemetry-exporter-otlp-proto-common=1.27.0
  - opentelemetry-exporter-otlp-proto-grpc=1.27.0
  - opentelemetry-instrumentation=0.48b0
  - opentelemetry-instrumentation-asgi=0.48b0
  - opentelemetry-instrumentation-fastapi=0.48b0
  - opentelemetry-proto=1.27.0
  - opentelemetry-sdk=1.27.0
  - opentelemetry-semantic-conventions=0.48b0
  - opentelemetry-util-http=0.48b0
  - orc=2.0.1
  - orjson=3.10.7
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pillow=9.2.0
  - pip=24.2
  - platformdirs=3.10.0
  - posthog=3.6.5
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.2.0
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pthreads-win32=2.9.1
  - pulsar-client=3.5.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pydantic=2.9.2
  - pydantic-core=2.23.4
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pymysql=1.0.2
  - pyopenssl=24.2.1
  - pypika=0.48.9
  - pyproject_hooks=1.2.0
  - pyreadline3=3.5.4
  - pysocks=1.7.1
  - python=3.11.9
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-kubernetes=31.0.0
  - python-multipart=0.0.12
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - re2=2023.09.01
  - referencing=0.30.2
  - regex=2024.9.11
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.2
  - rpds-py=0.10.6
  - rsa=4.9
  - send2trash=1.8.2
  - setuptools=75.1.0
  - shellingham=1.5.4
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=2.0.35
  - stack_data=0.2.0
  - starlette=0.39.2
  - streamlit=1.38.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tenacity=8.5.0
  - terminado=0.17.1
  - tiktoken=0.8.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.20.1
  - toml=0.10.2
  - tomli=2.0.2
  - toolz=0.12.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - uvicorn=0.31.1
  - uvicorn-standard=0.31.1
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - watchdog=4.0.1
  - watchfiles=0.24.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=13.1
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - win32_setctime=1.1.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.14.0
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: C:\Users\tangb\anaconda3\envs\GROQ_ENV
